/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Store;

import hany.DBConnect;
import java.awt.ComponentOrientation;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author amnassar
 */
public final class storesell extends javax.swing.JInternalFrame {

    /**
     * Creates new form book
     */
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    public String y;
    public String datee;
    public Calendar cal;
    String dayyy;
    public String fulldatee;

    public storesell() throws IOException {
        initComponents();
        con = DBConnect.connect();
        clear();
        Bill_id();
        comboxfromcombo();
        process_id();
        TableCellRenderer rendererFromHeader = tdetails.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tdetails.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tdetails.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        tdetails.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        tdetails.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        cal = new GregorianCalendar();

        int month = cal.get(Calendar.MONTH) + 1;
        int year = cal.get(Calendar.YEAR);
        int dayy = cal.get(Calendar.DAY_OF_MONTH);
        dayyy = String.valueOf(dayy);
        if (dayy == 1 || dayy == 2 || dayy == 3 || dayy == 4
                || dayy == 5 || dayy == 6 || dayy == 7 || dayy == 8 || dayy == 9) {
            dayyy = String.valueOf(dayy);
            dayyy = "0" + dayyy;
        }
        date1.setText(year + "-" + month + "-" + dayyy);
        datee = date1.getText().toString();
        available.setText("0");
        number1.setText("0");
        TimeZone tz = TimeZone.getTimeZone("GMT+02");
        Calendar c = Calendar.getInstance(tz);
        String time = String.format("%02d", c.get(Calendar.HOUR_OF_DAY)) + ":"
                + String.format("%02d", c.get(Calendar.MINUTE));
        fulldatee = datee + " " + time;
        items();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        cmitem = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        available = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tdetails = new javax.swing.JTable();
        total = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        number1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        cmname = new javax.swing.JComboBox();
        save5 = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        name2 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        idnumber4 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        page1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        delete3 = new javax.swing.JButton();
        save2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        serialid1 = new javax.swing.JLabel();
        date3 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        serial3 = new javax.swing.JTextField();
        number2 = new javax.swing.JTextField();
        date1 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        doctorname = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        cmvisa1 = new javax.swing.JComboBox();
        jLabel44 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        visa1 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        phone1 = new javax.swing.JLabel();
        p5 = new javax.swing.JLabel();
        phone3 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        p6 = new javax.swing.JLabel();
        idnumber5 = new javax.swing.JLabel();
        logserial = new javax.swing.JLabel();
        serial = new javax.swing.JLabel();

        jLabel16.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/71847608-close-up-of-handshake-on-city-background-with-abstract-sunlight-partnership-concept-double-exposure.jpg"))); // NOI18N

        setMaximumSize(new java.awt.Dimension(980, 690));
        setMinimumSize(new java.awt.Dimension(980, 690));
        setPreferredSize(new java.awt.Dimension(980, 690));

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));
        jPanel13.setForeground(new java.awt.Color(255, 255, 255));
        jPanel13.setMinimumSize(new java.awt.Dimension(90, 34));
        jPanel13.setPreferredSize(new java.awt.Dimension(970, 690));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel22.setText("المنتج");
        jPanel13.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 130, 80, -1));

        cmitem.setEditable(true);
        cmitem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        cmitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmitemActionPerformed(evt);
            }
        });
        jPanel13.add(cmitem, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 270, 30));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel25.setText("سعر المنتج");
        jPanel13.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 180, 110, 30));

        price.setEditable(false);
        price.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel13.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 90, 30));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel36.setText("المتاح");
        jPanel13.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 60, 30));

        available.setEditable(false);
        available.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        available.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel13.add(available, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 80, 30));

        tdetails.setBackground(new java.awt.Color(138, 203, 195));
        tdetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "الكود", "اسم المنتج", "كود المنتج", "العدد"
            }
        ));
        tdetails.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tdetails.setRowHeight(25);
        tdetails.setRowMargin(2);
        tdetails.setSelectionBackground(new java.awt.Color(204, 255, 255));
        tdetails.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tdetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tdetails);
        if (tdetails.getColumnModel().getColumnCount() > 0) {
            tdetails.getColumnModel().getColumn(0).setMinWidth(1);
            tdetails.getColumnModel().getColumn(0).setPreferredWidth(1);
            tdetails.getColumnModel().getColumn(0).setMaxWidth(1);
        }

        jPanel13.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 920, 200));

        total.setEditable(false);
        total.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        total.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        total.setText("0");
        jPanel13.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 80, 30));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel28.setText("المجموع");
        jPanel13.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 90, 30));

        number1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        number1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        number1.setText("1");
        number1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                number1KeyReleased(evt);
            }
        });
        jPanel13.add(number1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 90, 30));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel30.setText("اسم العميل");
        jPanel13.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, -1, -1));

        name1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1ActionPerformed(evt);
            }
        });
        name1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                name1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                name1KeyTyped(evt);
            }
        });
        jPanel13.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 190, 30));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel21.setText("العميل");
        jPanel13.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 70, -1));

        cmname.setEditable(true);
        cmname.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        cmname.setAutoscrolls(true);
        cmname.setDoubleBuffered(true);
        cmname.setFocusCycleRoot(true);
        cmname.setFocusTraversalPolicyProvider(true);
        cmname.setInheritsPopupMenu(true);
        cmname.setRequestFocusEnabled(true);
        cmname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmnameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmnameMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmnameMousePressed(evt);
            }
        });
        cmname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmnameActionPerformed(evt);
            }
        });
        cmname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmnameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmnameKeyTyped(evt);
            }
        });
        jPanel13.add(cmname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 260, 30));

        save5.setBackground(new java.awt.Color(156, 166, 187));
        save5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        save5.setForeground(new java.awt.Color(255, 255, 255));
        save5.setText("جديد");
        save5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save5ActionPerformed(evt);
            }
        });
        jPanel13.add(save5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 30, 30));

        jLabel43.setBackground(new java.awt.Color(255, 255, 255));
        jLabel43.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel43.setText("اسم العميل");
        jPanel13.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 70, -1, -1));

        name2.setEditable(false);
        name2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        name2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel13.add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 190, 30));

        jLabel47.setBackground(new java.awt.Color(255, 255, 255));
        jLabel47.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel47.setText("رقم قومي");
        jPanel13.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 100, 30));

        idnumber4.setEditable(false);
        idnumber4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        idnumber4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel13.add(idnumber4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 170, 30));

        jLabel48.setBackground(new java.awt.Color(255, 255, 255));
        jLabel48.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel48.setText("الصفحه");
        jPanel13.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 80, 30));

        page1.setEditable(false);
        page1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        page1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel13.add(page1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 90, 30));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel32.setText("العدد");
        jPanel13.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 230, 60, 30));

        delete3.setBackground(new java.awt.Color(138, 203, 195));
        delete3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        delete3.setText("مسح");
        delete3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete3ActionPerformed(evt);
            }
        });
        jPanel13.add(delete3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 170, 40));

        save2.setBackground(new java.awt.Color(138, 203, 195));
        save2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        save2.setText("حفظ");
        save2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save2ActionPerformed(evt);
            }
        });
        jPanel13.add(save2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 100, 50));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nYwGq3.jpg"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 2));
        jPanel13.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 720));

        serialid1.setText("jLabel1");
        jPanel13.add(serialid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 650, -1, -1));

        date3.setText("jLabel1");
        jPanel13.add(date3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 80, -1, -1));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel35.setText("Number");
        jPanel13.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, -1));

        serial3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        serial3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                serial3KeyPressed(evt);
            }
        });
        jPanel13.add(serial3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 650, 210, 30));

        number2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        number2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        number2.setText("0");
        number2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                number2KeyReleased(evt);
            }
        });
        jPanel13.add(number2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 650, 70, 30));

        date1.setText("jLabel1");
        jPanel13.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 180, -1, -1));

        t6.setEditable(false);
        t6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        t6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel13.add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, 180, 30));

        doctorname.setText("jLabel1");
        jPanel13.add(doctorname, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, -1, -1));

        jLabel50.setBackground(new java.awt.Color(255, 255, 255));
        jLabel50.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel50.setText("الضامن 1");
        jPanel13.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 190, 120, -1));

        t4.setEditable(false);
        t4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        t4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel13.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 650, 180, 30));

        jLabel55.setBackground(new java.awt.Color(255, 255, 255));
        jLabel55.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel55.setText("النوع");
        jPanel13.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 240, 80, 30));

        cmvisa1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "عادي", "فيزا" }));
        jPanel13.add(cmvisa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, 120, 30));

        jLabel44.setBackground(new java.awt.Color(255, 255, 255));
        jLabel44.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel44.setText("رقم");
        jPanel13.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, -1, 30));

        jLabel52.setBackground(new java.awt.Color(255, 255, 255));
        jLabel52.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel52.setText("الضامن 2");
        jPanel13.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 100, 30));

        t5.setEditable(false);
        t5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        t5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel13.add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 610, 170, 30));

        visa1.setEditable(false);
        visa1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        visa1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel13.add(visa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 660, 170, 30));

        jLabel53.setBackground(new java.awt.Color(255, 255, 255));
        jLabel53.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel53.setText("الضامن 3");
        jPanel13.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 100, 30));

        phone1.setText("jLabel1");
        jPanel13.add(phone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        p5.setText("jLabel4");
        jPanel13.add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 290, -1, -1));

        phone3.setText("jLabel4");
        jPanel13.add(phone3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        p4.setText("jLabel1");
        jPanel13.add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 300, -1, -1));

        p6.setText("jLabel6");
        jPanel13.add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 290, -1, -1));

        idnumber5.setText("jLabel1");
        jPanel13.add(idnumber5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 280, -1, -1));

        logserial.setText("jLabel1");
        jPanel13.add(logserial, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 530, -1, -1));

        serial.setText("jLabel1");
        jPanel13.add(serial, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 570, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tdetailsMouseClicked
        DefaultTableModel tmodel = (DefaultTableModel) tdetails.getModel();
        //bid,name, price, publisher, book_type, b_code, date, category
        int selectrowindex = tdetails.getSelectedRow();
        serialid1.setText(tmodel.getValueAt(selectrowindex, 0).toString());
        number2.setText(tmodel.getValueAt(selectrowindex, 3).toString());
        serial3.setText(tmodel.getValueAt(selectrowindex, 2).toString());
    }//GEN-LAST:event_tdetailsMouseClicked

    private void serial3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serial3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_serial3KeyPressed

    private void number1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_number1KeyReleased
        double numberr = Double.parseDouble(number1.getText());
        double pricee = Double.parseDouble(price.getText());
        double totall = numberr * pricee;
        total.setText("" + totall);
    }//GEN-LAST:event_number1KeyReleased

    private void delete3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete3ActionPerformed

    }//GEN-LAST:event_delete3ActionPerformed

    private void save2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save2ActionPerformed
        Bill_id();
        double pricee = Double.parseDouble(price.getText());
        double paidd = Double.parseDouble(price.getText());
        double numberr = Integer.parseInt(number1.getText());
        double totall = (pricee * numberr) - paidd;
        String dayy = null;
        double dailypricee = 0;
        String namee = cmname.getSelectedItem().toString();
        String itemm = cmitem.getSelectedItem().toString();
        String pagee = page1.getText().toString();
        double total = pricee - dailypricee;
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "هل تريد حفظ العمليه", "تاكيد العمليه", dialogButton);
        if (dialogResult == 0) {

            try {
                String sql = "INSERT INTO eslam.buy (idnumber,number,date,name,kest,serial,item,page,price,dailyprice,paid,total,phone,phone2,p1,p2,p3,t1,t2,t3)"
                        + " VALUES "
                        + "('" + idnumber5.getText() + "','" + numberr + "','" + date1.getText().toString() + "',"
                        + "'" + namee + "','old','" + serial.getText() + "','" + itemm + "','" + pagee + "','" + pricee + "',"
                        + "'" + dailypricee + "','" + paidd + "','" + totall + "','" + phone1.getText() + "','" + phone3.getText() + "','" + p4.getText() + "',"
                        + "'" + p5.getText() + "','" + p6.getText() + "','" + t4.getText() + "','" + t5.getText() + "','" + t6.getText() + "')";
                pst = (PreparedStatement) con.prepareStatement(sql);
                pst.execute();
                String sqll = "INSERT INTO eslam.logs (type,buyserial,serial,name,item,day,date,dailyprice,remaining,page,fulldate,beforee) VALUES"
                        + " ('كاش','" + serial.getText() + "','" + logserial.getText() + "',"
                        + ",'" + namee + "','" + itemm + "','" + dayy + "','" + datee + "',"
                        + "'" + dailypricee + "','" + total + "','" + pagee + "','" + fulldatee + "','" + price.getText() + "')";
                pst = (PreparedStatement) con.prepareStatement(sqll);
                pst.execute();

                // done();
                TimeZone tz = TimeZone.getTimeZone("GMT+02");
                Calendar c = Calendar.getInstance(tz);
                String time = String.format("%02d", c.get(Calendar.HOUR_OF_DAY)) + ":"
                        + String.format("%02d", c.get(Calendar.MINUTE));
                String fulldatee = datee + " " + time;
                String sqlz = "INSERT INTO eslam.amounts (type,buyserial,name,item,day,date,dailyprice,remaining,page) VALUES"
                        + " ('كاش','" + serial.getText() + "','" + namee + "','" + itemm + "','" + dayy + "','" + fulldatee + "','" + dailypricee + "','" + totall + "','" + pagee + "')";

                pst = (PreparedStatement) con.prepareStatement(sqlz);
                pst.execute();
                process_id();
                String sqla1d = "UPDATE eslam.storeitemlist SET number =number-" + number1.getText() + " WHERE  name='" + cmitem.getSelectedItem().toString() + "'";
                pst = (PreparedStatement) con.prepareStatement(sqla1d);
                pst.executeUpdate();
                String sqll33 = "INSERT INTO eslam.storeitemlogs (name,supplier,number,type,date,fulldate,price) "
                        + "VALUES('" + cmitem.getSelectedItem().toString() + "','" + name2.getText() + "','" + number1.getText() + "','تقسيط','" + datee + "','" + fulldatee + "','" + price.getText() + "')";
                pst = (PreparedStatement) con.prepareStatement(sqll33);
                pst.execute();

                JOptionPane.showMessageDialog(null, "تم الشراء بنجاح");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            if (paidd > 0) {

            }

        } else {
            JOptionPane.showMessageDialog(this, " تم الغاء العمليه");

        }
    }//GEN-LAST:event_save2ActionPerformed

    private void number2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_number2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_number2KeyReleased

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name1ActionPerformed

    private void name1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            try {
                String sqll = "SELECT name  FROM eslam.customer ";

                pst = (PreparedStatement) con.prepareStatement(sqll);

                rs = pst.executeQuery();

                while (rs.next()) {

                    String name = rs.getString("name");

                    cmname.removeItem(name);

                }
            } catch (SQLException ex) {

            }
            cmname.setSelectedIndex(0);
            try {

                String sql = "SELECT name  FROM eslam.customer  where name like '%" + name1.getText() + "%' order by name ";
                pst = (PreparedStatement) con.prepareStatement(sql);
                rs = pst.executeQuery();
                while (rs.next()) {
                    String name = rs.getString("name");

                    cmname.addItem(name);
                }

                cmname.requestFocus();

            } catch (SQLException ex) {

            }
        }
    }//GEN-LAST:event_name1KeyPressed

    private void name1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name1KeyTyped

    }//GEN-LAST:event_name1KeyTyped

    private void cmnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmnameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmnameMouseClicked

    private void cmnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmnameMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cmnameMouseEntered

    private void cmnameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmnameMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmnameMousePressed

    private void cmnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmnameActionPerformed

    }//GEN-LAST:event_cmnameActionPerformed

    private void cmnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmnameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmnameKeyPressed

    private void cmnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmnameKeyTyped

    }//GEN-LAST:event_cmnameKeyTyped

    private void save5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save5ActionPerformed

    }//GEN-LAST:event_save5ActionPerformed

    private void cmitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmitemActionPerformed
        Object obj = evt.getSource();
        if (obj == cmitem) {
            try {
                String sql = "SELECT *  FROM eslam.storeitemlist where name ='" + cmitem.getSelectedItem().toString() + "'";
                pst = (PreparedStatement) con.prepareStatement(sql);
                rs = pst.executeQuery();
                while (rs.next()) {
                    price.setText(rs.getString("price"));
                    available.setText(rs.getString("number"));

                }

            } catch (SQLException ex) {

            }
        }
    }//GEN-LAST:event_cmitemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField available;
    private javax.swing.JComboBox cmitem;
    private javax.swing.JComboBox cmname;
    private javax.swing.JComboBox cmvisa1;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date3;
    private javax.swing.JButton delete3;
    private javax.swing.JLabel doctorname;
    private javax.swing.JTextField idnumber4;
    private javax.swing.JLabel idnumber5;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logserial;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField name2;
    private javax.swing.JTextField number1;
    private javax.swing.JTextField number2;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel p5;
    private javax.swing.JLabel p6;
    private javax.swing.JTextField page1;
    private javax.swing.JLabel phone1;
    private javax.swing.JLabel phone3;
    private javax.swing.JTextField price;
    private javax.swing.JButton save2;
    private javax.swing.JButton save5;
    private javax.swing.JLabel serial;
    private javax.swing.JTextField serial3;
    private javax.swing.JLabel serialid1;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTable tdetails;
    private javax.swing.JTextField total;
    private javax.swing.JTextField visa1;
    // End of variables declaration//GEN-END:variables
public void clear() {
        available.setText("");
        number1.setText("");
        price.setText("");
        serial3.setText("");
        number2.setText("");

    }

    public void comboxfromcombo() {
        cmname.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent event) {
                JComboBox cmsupplier = (JComboBox) event.getSource();

                Object item = event.getItem();
                try {
                    String sql = "SELECT * FROM eslam.customer where name='" + cmname.getSelectedItem().toString() + "'";
                    pst = (PreparedStatement) con.prepareStatement(sql);
                    rs = pst.executeQuery();
                    while (rs.next()) {
                        name2.setText(rs.getString("name"));
                        idnumber4.setText(rs.getString("idnumber"));
                        page1.setText(rs.getString("page"));
                        t4.setText(rs.getString("t1"));
                        t5.setText(rs.getString("t2"));
                        t6.setText(rs.getString("t3"));
                        p4.setText(rs.getString("p1"));
                        p5.setText(rs.getString("p2"));
                        p6.setText(rs.getString("p3"));
                        phone1.setText(rs.getString("phone"));
                        phone3.setText(rs.getString("phone2"));
                        idnumber5.setText(rs.getString("idnumber"));
                        visa1.setText(rs.getString("visanumber"));
                        cmvisa1.setSelectedItem(rs.getString("visa"));
                    }

                } catch (SQLException ex) {

                }
            }
        });

    }

    public void Bill_id() {

        try {
            String sql = "SELECT serial FROM eslam.logs where id=(select max(id)FROm eslam.logs )";
            pst = (PreparedStatement) con.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                String rnno = rs.getString("serial");
                int co = rnno.length();
                String txt = rnno.substring(0, 3);
                String num = rnno.substring(3, co);
                int n = Integer.parseInt(num);
                n++;
                String snum = Integer.toString(n);
                String ftxt = txt + snum;
                logserial.setText(ftxt);
            } else {
                logserial.setText("BN-1001");
            }
        } catch (SQLException ex) {

        }

    }

    public void process_id() {

        try {
            String sql = "SELECT serial FROM eslam.buy where id=(select max(id)FROm eslam.buy )";
            pst = (PreparedStatement) con.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                String rnno = rs.getString("serial");
                int co = rnno.length();
                String txt = rnno.substring(0, 3);
                String num = rnno.substring(3, co);
                int n = Integer.parseInt(num);
                n++;
                String snum = Integer.toString(n);
                String ftxt = txt + snum;
                serial.setText(ftxt);
            } else {
                serial.setText("PN-1001");
            }
        } catch (SQLException ex) {

        }

    }

    public void items() {
        try {
            String sql = "SELECT name  FROM eslam.storeitemlist ";
            pst = (PreparedStatement) con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String name = rs.getString("name");

                cmitem.addItem(name);

            }

        } catch (SQLException ex) {

        }
    }
}
